language: python
python: 2.7
env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=PyLEMS_NeuroML2
    - OMV_ENGINE=jNeuroML_Brain
install: 
  - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
script:
  - omv all -V
